// <auto-generated />
using System;
using GameChooserDiscord.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameChooserDiscord.Migrations
{
    [DbContext(typeof(GameChoiceContext))]
    partial class GameChoiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("GameChooserDiscord.Models.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesChosen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesDrawn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Fruits");
                });

            modelBuilder.Entity("GameChooserDiscord.Models.GameCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesChosen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesDrawn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimesUnheardOf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WikipediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
